applications:
    app:
        type: "php:8.2"

        build:
            flavor: composer

        runtime:
            extensions:
                - intl
                - opcache
                - pdo_mysql
                - sodium
            packages:
                - jpegoptim
                - pngquant

        mounts:
            "/var": "shared:files/var"
            "/var/log": "shared:files/logs"
            "/public/uploads": "shared:files/uploads"

        relationships:
            database: "mysql:mysql"

        variables:
            php:
                display_errors: '0'
                display_startup_errors: '0'
                max_execution_time: '30'
                memory_limit: '256M'
                zend.assertions: '-1'
                assert.active: '0'
                session.use_strict_mode: '1'
                zend.detect_unicode: '0'
                realpath_cache_ttl: '7200'
                session.gc_probability: '0'
            env:
                APP_ENV: "prod"
                APP_DEBUG: "0"
                SYMFONY_SKIP_AUTO_SCRIPTS: "1"

        web:
            locations:
                "/":
                    root: "public"
                    passthru: "/index.php"
                    expires: -1
                    scripts: true
                    allow: true

        hooks:
            build: |
                set -e
                find public/static/img -type f \( -name '*.jpg' -o -name '*.jpeg' \) -exec jpegoptim --strip-all --max=82 {} + || true
                find public/static/img -type f -name '*.png' -exec pngquant --force --ext .png --quality=65-80 {} + || true
                composer install --no-dev --optimize-autoloader --apcu-autoloader
                php bin/console importmap:install --no-interaction || true
                php bin/console assets:install --relative public
            deploy: |
                set -e
                php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration || true
                php bin/console cache:clear --env=prod

