applications:
    app:
        type: "php:8.2"

        build:
            flavor: composer

        runtime:
            extensions:
                - intl
                - opcache
                - pdo_mysql
                - sodium

        mounts:
            "/var": "shared:files/var"
            "/var/log": "shared:files/logs"
            "/public/uploads": "shared:files/uploads"

        relationships:
            database: "mysql:mysql"

        variables:
            env:
                APP_ENV: "prod"
                APP_DEBUG: "0"
                APP_SECRET: "@app.secret"

        web:
            locations:
                "/":
                    root: "public"
                    passthru: "/index.php"
                    expires: -1
                    scripts: true
                    allow: true

        hooks:
            build: |
                set -e
                composer install --no-dev --optimize-autoloader --apcu-autoloader
            deploy: |
                set -e
                php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration || true
                php bin/console cache:clear

