applications:
    app:
        type: "php:8.2"

        build:
            flavor: composer

        runtime:
            extensions:
                - intl
                - opcache
                - pdo_mysql
                - sodium
            php_ini:
                display_errors: '0'
                display_startup_errors: '0'
                max_execution_time: '30'
                zend.assertions: '-1'

        mounts:
            "/var": "shared:files/var"
            "/var/log": "shared:files/logs"
            "/public/uploads": "shared:files/uploads"

        relationships:
            database: "mysql:mysql"

        variables:
            env:
                APP_ENV: "prod"
                APP_DEBUG: "0"
                SYMFONY_SKIP_AUTO_SCRIPTS: "1"

        web:
            locations:
                "/":
                    root: "public"
                    passthru: "/index.php"
                    expires: -1
                    scripts: true
                    allow: true

        hooks:
            build: |
                set -e
                composer install --no-dev --optimize-autoloader --apcu-autoloader
                php bin/console importmap:install --no-interaction || true
                php bin/console assets:install --relative public
            deploy: |
                set -e
                php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration || true
                php bin/console cache:clear --env=prod

